import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ThemeProvider } from "./components/theme-provider";
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const lato = localFont({
  src: [
    {
      path: '../public/fonts/Lato/Lato-Regular.ttf',
      weight: '400'
    },
    {
      path: '../public/fonts/Lato/Lato-Bold.ttf',
      weight: '700'
    }
  ],
  variable: '--font-lato'
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} font-sans text-base tracking-widest` }>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar/>
        <main className="max-w-7xl mx-auto">
          {children}
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
